name: Build Flet APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'  # Новая версия с Dart 3.9+
        channel: 'stable'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.7'
        
    - name: Install Flet
      run: |
        python -m pip install --upgrade pip
        pip install flet
        
    - name: Build APK
      run: |
        flet build apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/apk/*.apk
