name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.13.7'
    - run: pip install flet
    - run: flet build apk
    - uses: actions/upload-artifact@v2
      with:
        name: app
        path: build/apk/*.apk
